import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { Theme } from "@radix-ui/themes";
import "@radix-ui/themes/styles.css";
import { Navbar } from "./components/navbar";
import KampusBg from "./components/kampusbg";

const textFont = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={textFont.className}>
        <main className="flex min-h-screen items-center justify-between">
          <Navbar />
          <Theme appearance="dark">{children}</Theme>
        </main>
      </body>
    </html>
  );
}
